export const TREE_FETCH_REQUEST      = 'TREE_FETCH_REQUEST'
export const TREE_FETCH_RESPONSE     = 'TREE_FETCH_RESPONSE'
export const TREE_FETCH_FAILURE      = 'TREE_FETCH_FAILURE'
export const TREE_TOGGLE_COLLAPSED   = 'TREE_TOGGLE_COLLAPSED'